backend.pushbullet:
    disabled: False
    logging: DEBUG
    token: your_pushbullet_token_here
    device: turing

# device_id: <your_device_id> (default: current hostname)
# debug: True (default: False)

