language: python
dist: xenial
python:
  - "3.7"

install: "pip install -r .travis.requirements"

script: pytest

notifications:
    email:
        recipients:
            - blacklight86@gmail.com
        on_success: change
        on_failure: change

services:
    - redis-server

git:
    submodules: false

