# -*- coding: utf-8 -*-
# flake8: noqa
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cast_channel.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 7, 35, 1, '', 'cast_channel.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x12\x63\x61st_channel.proto\"\xab\x02\n\x0b\x43\x61stMessage\x12\x36\n\x10protocol_version\x18\x01 \x02(\x0e\x32\x1c.CastMessage.ProtocolVersion\x12\x11\n\tsource_id\x18\x02 \x02(\t\x12\x16\n\x0e\x64\x65stination_id\x18\x03 \x02(\t\x12\x11\n\tnamespace\x18\x04 \x02(\t\x12.\n\x0cpayload_type\x18\x05 \x02(\x0e\x32\x18.CastMessage.PayloadType\x12\x14\n\x0cpayload_utf8\x18\x06 \x01(\t\x12\x16\n\x0epayload_binary\x18\x07 \x01(\x0c\"!\n\x0fProtocolVersion\x12\x0e\n\nCASTV2_1_0\x10\x00\"%\n\x0bPayloadType\x12\n\n\x06STRING\x10\x00\x12\n\n\x06\x42INARY\x10\x01\"\x0f\n\rAuthChallenge\"B\n\x0c\x41uthResponse\x12\x11\n\tsignature\x18\x01 \x02(\x0c\x12\x1f\n\x17\x63lient_auth_certificate\x18\x02 \x02(\x0c\"b\n\tAuthError\x12(\n\nerror_type\x18\x01 \x02(\x0e\x32\x14.AuthError.ErrorType\"+\n\tErrorType\x12\x12\n\x0eINTERNAL_ERROR\x10\x00\x12\n\n\x06NO_TLS\x10\x01\"r\n\x11\x44\x65viceAuthMessage\x12!\n\tchallenge\x18\x01 \x01(\x0b\x32\x0e.AuthChallenge\x12\x1f\n\x08response\x18\x02 \x01(\x0b\x32\r.AuthResponse\x12\x19\n\x05\x65rror\x18\x03 \x01(\x0b\x32\n.AuthErrorB\x02H\x03'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cast_channel_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals['DESCRIPTOR']._loaded_options = None
    _globals['DESCRIPTOR']._serialized_options = b'H\003'
    _globals['_CASTMESSAGE']._serialized_start = 23
    _globals['_CASTMESSAGE']._serialized_end = 322
    _globals['_CASTMESSAGE_PROTOCOLVERSION']._serialized_start = 250
    _globals['_CASTMESSAGE_PROTOCOLVERSION']._serialized_end = 283
    _globals['_CASTMESSAGE_PAYLOADTYPE']._serialized_start = 285
    _globals['_CASTMESSAGE_PAYLOADTYPE']._serialized_end = 322
    _globals['_AUTHCHALLENGE']._serialized_start = 324
    _globals['_AUTHCHALLENGE']._serialized_end = 339
    _globals['_AUTHRESPONSE']._serialized_start = 341
    _globals['_AUTHRESPONSE']._serialized_end = 407
    _globals['_AUTHERROR']._serialized_start = 409
    _globals['_AUTHERROR']._serialized_end = 507
    _globals['_AUTHERROR_ERRORTYPE']._serialized_start = 464
    _globals['_AUTHERROR_ERRORTYPE']._serialized_end = 507
    _globals['_DEVICEAUTHMESSAGE']._serialized_start = 509
    _globals['_DEVICEAUTHMESSAGE']._serialized_end = 623
# @@protoc_insertion_point(module_scope)
